{
  "SchemaVersion": 2,
  "ArtifactName": "https://github.com/knqyf263/trivy-ci-test",
  "ArtifactType": "repository",
  "Metadata": {
    "ImageConfig": {
      "architecture": "",
      "created": "0001-01-01T00:00:00Z",
      "os": "",
      "rootfs": {
        "type": "",
        "diff_ids": null
      },
      "config": {}
    }
  },
  "Results": [
    {
      "Target": "Cargo.lock",
      "Class": "lang-pkgs",
      "Type": "cargo",
      "Vulnerabilities": [
        {
          "VulnerabilityID": "CVE-2019-15542",
          "PkgName": "ammonia",
          "InstalledVersion": "1.9.0",
          "FixedVersion": "2.1.0",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-15542",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory Rust",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Arust"
          },
          "Title": "Uncontrolled recursion in ammonia",
          "Description": "An issue was discovered in the ammonia crate before 2.1.0 for Rust. There is uncontrolled recursion during HTML DOM tree serialization.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-674"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V2Score": 5,
              "V3Score": 7.5
            }
          },
          "References": [
            "https://github.com/advisories/GHSA-5hp8-35wj-m525",
            "https://github.com/rust-ammonia/ammonia/blob/master/CHANGELOG.md#210",
            "https://nvd.nist.gov/vuln/detail/CVE-2019-15542",
            "https://rustsec.org/advisories/RUSTSEC-2019-0001.html"
          ],
          "PublishedDate": "2019-08-26T18:15:00Z",
          "LastModifiedDate": "2020-08-24T17:37:00Z"
        },
        {
          "VulnerabilityID": "CVE-2021-38193",
          "PkgName": "ammonia",
          "InstalledVersion": "1.9.0",
          "FixedVersion": "2.1.3, 3.1.0",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-38193",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory Rust",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Arust"
          },
          "Title": "An issue was discovered in the ammonia crate before 3.1.0 for Rust. XS ...",
          "Description": "An issue was discovered in the ammonia crate before 3.1.0 for Rust. XSS can occur because the parsing differences for HTML, SVG, and MathML are mishandled, a similar issue to CVE-2020-26870.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-79"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V3Score": 6.1
            },
            "nvd": {
              "V2Vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V2Score": 4.3,
              "V3Score": 6.1
            }
          },
          "References": [
            "https://github.com/advisories/GHSA-5325-xw5m-phm3",
            "https://github.com/rust-ammonia/ammonia/pull/142",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-38193",
            "https://raw.githubusercontent.com/rustsec/advisory-db/main/crates/ammonia/RUSTSEC-2021-0074.md",
            "https://rustsec.org/advisories/RUSTSEC-2021-0074.html"
          ],
          "PublishedDate": "2021-08-08T06:15:00Z",
          "LastModifiedDate": "2021-08-16T16:37:00Z"
        },
        {
          "VulnerabilityID": "CVE-2018-20997",
          "PkgName": "openssl",
          "InstalledVersion": "0.8.3",
          "FixedVersion": "0.10.9",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2018-20997",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory Rust",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Arust"
          },
          "Title": "Use after free in openssl",
          "Description": "An issue was discovered in the openssl crate before 0.10.9 for Rust. A use-after-free occurs in CMS Signing.",
          "Severity": "CRITICAL",
          "CweIDs": [
            "CWE-416"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V2Score": 7.5,
              "V3Score": 9.8
            }
          },
          "References": [
            "https://github.com/advisories/GHSA-xjxc-vfw2-cg96",
            "https://github.com/sfackler/rust-openssl/pull/942",
            "https://nvd.nist.gov/vuln/detail/CVE-2018-20997",
            "https://rustsec.org/advisories/RUSTSEC-2018-0010.html"
          ],
          "PublishedDate": "2019-08-26T18:15:00Z",
          "LastModifiedDate": "2019-08-30T12:41:00Z"
        },
        {
          "VulnerabilityID": "CVE-2016-10931",
          "PkgName": "openssl",
          "InstalledVersion": "0.8.3",
          "FixedVersion": "0.9.0",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2016-10931",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory Rust",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Arust"
          },
          "Title": "Improper Certificate Validation in openssl",
          "Description": "An issue was discovered in the openssl crate before 0.9.0 for Rust. There is an SSL/TLS man-in-the-middle vulnerability because certificate verification is off by default and there is no API for hostname verification.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-295"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 8.1
            },
            "nvd": {
              "V2Vector": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
              "V3Vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V2Score": 6.8,
              "V3Score": 8.1
            }
          },
          "References": [
            "https://github.com/advisories/GHSA-34p9-f4q3-c4r7",
            "https://github.com/sfackler/rust-openssl/releases/tag/v0.9.0",
            "https://nvd.nist.gov/vuln/detail/CVE-2016-10931",
            "https://rustsec.org/advisories/RUSTSEC-2016-0001.html"
          ],
          "PublishedDate": "2019-08-26T12:15:00Z",
          "LastModifiedDate": "2019-09-03T20:31:00Z"
        },
        {
          "VulnerabilityID": "CVE-2020-25576",
          "PkgName": "rand_core",
          "InstalledVersion": "0.4.0",
          "FixedVersion": "0.3.1, 0.4.2",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-25576",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory Rust",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Arust"
          },
          "Title": "An issue was discovered in the rand_core crate before 0.4.2 for Rust.  ...",
          "Description": "An issue was discovered in the rand_core crate before 0.4.2 for Rust. Casting of byte slices to integer slices mishandles alignment constraints.",
          "Severity": "CRITICAL",
          "CweIDs": [
            "CWE-704"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V2Score": 7.5,
              "V3Score": 9.8
            }
          },
          "References": [
            "https://github.com/advisories/GHSA-mmc9-pwm7-qj5w",
            "https://github.com/rust-random/rand/blob/master/rand_core/CHANGELOG.md#050---2019-06-06",
            "https://github.com/rust-random/rand/security/advisories/GHSA-mmc9-pwm7-qj5w",
            "https://rustsec.org/advisories/RUSTSEC-2019-0035.html"
          ],
          "PublishedDate": "2020-09-14T19:15:00Z",
          "LastModifiedDate": "2020-09-22T17:38:00Z"
        },
        {
          "VulnerabilityID": "CVE-2019-15551",
          "PkgName": "smallvec",
          "InstalledVersion": "0.6.9",
          "FixedVersion": "0.6.10",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-15551",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory Rust",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Arust"
          },
          "Title": "An issue was discovered in the smallvec crate before 0.6.10 for Rust.  ...",
          "Description": "An issue was discovered in the smallvec crate before 0.6.10 for Rust. There is a double free for certain grow attempts with the current capacity.",
          "Severity": "CRITICAL",
          "CweIDs": [
            "CWE-415"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V2Score": 7.5,
              "V3Score": 9.8
            }
          },
          "References": [
            "https://github.com/advisories/GHSA-mm7v-vpv8-xfc3",
            "https://github.com/servo/rust-smallvec/issues/148",
            "https://nvd.nist.gov/vuln/detail/CVE-2019-15551",
            "https://rustsec.org/advisories/RUSTSEC-2019-0009.html"
          ],
          "PublishedDate": "2019-08-26T15:15:00Z",
          "LastModifiedDate": "2019-09-03T15:02:00Z"
        },
        {
          "VulnerabilityID": "CVE-2019-15554",
          "PkgName": "smallvec",
          "InstalledVersion": "0.6.9",
          "FixedVersion": "0.6.10",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-15554",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory Rust",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Arust"
          },
          "Title": "An issue was discovered in the smallvec crate before 0.6.10 for Rust.  ...",
          "Description": "An issue was discovered in the smallvec crate before 0.6.10 for Rust. There is memory corruption for certain grow attempts with less than the current capacity.",
          "Severity": "CRITICAL",
          "CweIDs": [
            "CWE-787"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V2Score": 7.5,
              "V3Score": 9.8
            }
          },
          "References": [
            "https://github.com/advisories/GHSA-69gw-hgj3-45m7",
            "https://github.com/servo/rust-smallvec/issues/149",
            "https://nvd.nist.gov/vuln/detail/CVE-2019-15554",
            "https://rustsec.org/advisories/RUSTSEC-2019-0012.html"
          ],
          "PublishedDate": "2019-08-26T15:15:00Z",
          "LastModifiedDate": "2020-08-24T17:37:00Z"
        },
        {
          "VulnerabilityID": "CVE-2021-25900",
          "PkgName": "smallvec",
          "InstalledVersion": "0.6.9",
          "FixedVersion": "1.6.1, 0.6.14",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-25900",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory Rust",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Arust"
          },
          "Title": "An issue was discovered in the smallvec crate before 0.6.14 and 1.x be ...",
          "Description": "An issue was discovered in the smallvec crate before 0.6.14 and 1.x before 1.6.1 for Rust. There is a heap-based buffer overflow in SmallVec::insert_many.",
          "Severity": "CRITICAL",
          "CweIDs": [
            "CWE-787"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V2Score": 7.5,
              "V3Score": 9.8
            }
          },
          "References": [
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-25900",
            "https://github.com/advisories/GHSA-43w2-9j62-hq99",
            "https://github.com/servo/rust-smallvec/issues/252",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-25900",
            "https://rustsec.org/advisories/RUSTSEC-2021-0003.html"
          ],
          "PublishedDate": "2021-01-26T18:16:00Z",
          "LastModifiedDate": "2021-02-02T19:56:00Z"
        },
        {
          "VulnerabilityID": "CVE-2018-25023",
          "PkgName": "smallvec",
          "InstalledVersion": "0.6.9",
          "FixedVersion": "0.6.13",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2018-25023",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory Rust",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Arust"
          },
          "Title": "An issue was discovered in the smallvec crate before 0.6.13 for Rust.  ...",
          "Description": "An issue was discovered in the smallvec crate before 0.6.13 for Rust. It can create an uninitialized value of any type, including a reference type.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-908"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V2Score": 5,
              "V3Score": 7.5
            }
          },
          "References": [
            "https://github.com/advisories/GHSA-55m5-whcv-c49c",
            "https://nvd.nist.gov/vuln/detail/CVE-2018-25023",
            "https://raw.githubusercontent.com/rustsec/advisory-db/main/crates/smallvec/RUSTSEC-2018-0018.md",
            "https://rustsec.org/advisories/RUSTSEC-2018-0018.html"
          ],
          "PublishedDate": "2021-12-27T00:15:00Z",
          "LastModifiedDate": "2022-01-05T15:53:00Z"
        },
        {
          "VulnerabilityID": "GHSA-66p5-j55p-32r9",
          "PkgName": "smallvec",
          "InstalledVersion": "0.6.9",
          "FixedVersion": "0.6.13",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://github.com/advisories/GHSA-66p5-j55p-32r9",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory Rust",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Arust"
          },
          "Title": "smallvec creates uninitialized value of any type",
          "Description": "Affected versions of this crate called `mem::uninitialized()` to create values of a user-supplied type `T`.\nThis is unsound e.g. if `T` is a reference type (which must be non-null and thus may not remain uninitialized).\n \nThe flaw was corrected by avoiding the use of `mem::uninitialized()`, using `MaybeUninit` instead.\n",
          "Severity": "MEDIUM",
          "References": [
            "https://github.com/advisories/GHSA-66p5-j55p-32r9",
            "https://github.com/servo/rust-smallvec/issues/126",
            "https://github.com/servo/rust-smallvec/pull/162",
            "https://rustsec.org/advisories/RUSTSEC-2018-0018.html"
          ]
        }
      ]
    },
    {
      "Target": "Pipfile.lock",
      "Class": "lang-pkgs",
      "Type": "pipenv",
      "Vulnerabilities": [
        {
          "VulnerabilityID": "CVE-2021-42771",
          "PkgName": "babel",
          "InstalledVersion": "2.6.0",
          "FixedVersion": "2.9.1",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-42771",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "CVE-2021-20095 CVE-2021-42771 python-babel: Relative path traversal allows attacker to load arbitrary locale files and execute arbitrary code",
          "Description": "Babel.Locale in Babel before 2.9.1 allows attackers to load arbitrary locale .dat files (containing serialized Python objects) via directory traversal, leading to code execution.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 7.8
            },
            "nvd": {
              "V2Vector": "AV:L/AC:L/Au:N/C:C/I:C/A:C",
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
              "V2Score": 7.2,
              "V3Score": 7.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 7.8
            }
          },
          "References": [
            "https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-20095.json",
            "https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2021-42771.json",
            "https://access.redhat.com/security/cve/CVE-2021-42771",
            "https://github.com/advisories/GHSA-h4m5-qpfp-3mpv",
            "https://github.com/python-babel/babel/pull/782",
            "https://linux.oracle.com/cve/CVE-2021-42771.html",
            "https://linux.oracle.com/errata/ELSA-2021-4201.html",
            "https://lists.debian.org/debian-lts-announce/2021/10/msg00018.html",
            "https://lists.debian.org/debian-lts/2021/10/msg00040.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-42771",
            "https://www.debian.org/security/2021/dsa-5018",
            "https://www.tenable.com/security/research/tra-2021-14"
          ],
          "PublishedDate": "2021-10-20T21:15:00Z",
          "LastModifiedDate": "2021-12-14T21:22:00Z"
        },
        {
          "VulnerabilityID": "CVE-2021-23727",
          "PkgName": "celery",
          "InstalledVersion": "4.3.0",
          "FixedVersion": "5.2.2",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-23727",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "celery: stored command injection vulnerability may allow privileges escalation",
          "Description": "This affects the package celery before 5.2.2. It by default trusts the messages and metadata stored in backends (result stores). When reading task metadata from the backend, the data is deserialized. Given that an attacker can gain access to, or somehow manipulate the metadata within a celery backend, they could trigger a stored command injection vulnerability and potentially gain further access to the system.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-77"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:M/Au:S/C:P/I:P/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H",
              "V2Score": 6,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:C/C:H/I:H/A:H",
              "V3Score": 8
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2021-23727",
            "https://github.com/advisories/GHSA-q4xr-rc97-m4xx",
            "https://github.com/celery/celery/blob/master/Changelog.rst%23522",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SYXRGHWHD2WWMHBWCVD5ULVINPKNY3P5/",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-23727",
            "https://snyk.io/vuln/SNYK-PYTHON-CELERY-2314953"
          ],
          "PublishedDate": "2021-12-29T17:15:00Z",
          "LastModifiedDate": "2022-06-14T14:38:00Z"
        },
        {
          "VulnerabilityID": "CVE-2019-6975",
          "PkgName": "django",
          "InstalledVersion": "2.0.9",
          "FixedVersion": "1.11.19, 2.0.12, 2.1.7",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-6975",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "python-django: memory exhaustion in django.utils.numberformat.format()",
          "Description": "Django 1.11.x before 1.11.19, 2.0.x before 2.0.11, and 2.1.x before 2.1.6 allows Uncontrolled Memory Consumption via a malicious attacker-supplied value to the django.utils.numberformat.format() function.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-770"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V2Score": 5,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
              "V3Score": 5.3
            }
          },
          "References": [
            "http://www.securityfocus.com/bid/106964",
            "https://access.redhat.com/security/cve/CVE-2019-6975",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-6975",
            "https://docs.djangoproject.com/en/dev/releases/security/",
            "https://github.com/advisories/GHSA-wh4h-v3f2-r2pp",
            "https://groups.google.com/forum/#!topic/django-announce/WTwEAprR0IQ",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/66WMXHGBXD7GSM3PEXVCMCAGLMQYHZCU/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/",
            "https://nvd.nist.gov/vuln/detail/CVE-2019-6975",
            "https://seclists.org/bugtraq/2019/Jul/10",
            "https://ubuntu.com/security/notices/USN-3890-1",
            "https://usn.ubuntu.com/3890-1/",
            "https://www.debian.org/security/2019/dsa-4476",
            "https://www.djangoproject.com/weblog/2019/feb/11/security-releases/",
            "https://www.openwall.com/lists/oss-security/2019/02/11/1"
          ],
          "PublishedDate": "2019-02-11T13:29:00Z",
          "LastModifiedDate": "2020-08-24T17:37:00Z"
        },
        {
          "VulnerabilityID": "CVE-2019-3498",
          "PkgName": "django",
          "InstalledVersion": "2.0.9",
          "FixedVersion": "1.11.18, 2.0.10, 2.1.5",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-3498",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "python-django: Content spoofing via URL path in default 404 page",
          "Description": "In Django 1.11.x before 1.11.18, 2.0.x before 2.0.10, and 2.1.x before 2.1.5, an Improper Neutralization of Special Elements in Output Used by a Downstream Component issue exists in django.views.defaults.page_not_found(), leading to content spoofing (in a 404 error page) if a user fails to recognize that a crafted URL has malicious content.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-20"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 6.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
              "V2Score": 4.3,
              "V3Score": 6.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N",
              "V3Score": 4.3
            }
          },
          "References": [
            "http://www.securityfocus.com/bid/106453",
            "https://access.redhat.com/security/cve/CVE-2019-3498",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-3498",
            "https://docs.djangoproject.com/en/dev/releases/security/",
            "https://github.com/advisories/GHSA-337x-4q8g-prc5",
            "https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ",
            "https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/",
            "https://nvd.nist.gov/vuln/detail/CVE-2019-3498",
            "https://ubuntu.com/security/notices/USN-3851-1",
            "https://usn.ubuntu.com/3851-1/",
            "https://www.debian.org/security/2019/dsa-4363",
            "https://www.djangoproject.com/weblog/2019/jan/04/security-releases/"
          ],
          "PublishedDate": "2019-01-09T23:29:00Z",
          "LastModifiedDate": "2021-07-21T11:39:00Z"
        },
        {
          "VulnerabilityID": "CVE-2021-33203",
          "PkgName": "django",
          "InstalledVersion": "2.0.9",
          "FixedVersion": "2.2.24, 3.1.12, 3.2.4",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-33203",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "django: Potential directory traversal via ``admindocs``",
          "Description": "Django before 2.2.24, 3.x before 3.1.12, and 3.2.x before 3.2.4 has a potential directory traversal via django.contrib.admindocs. Staff members could use the TemplateDetailView view to check the existence of arbitrary files. Additionally, if (and only if) the default admindocs templates have been customized by application developers to also show file contents, then not only the existence but also the file contents would have been exposed. In other words, there is directory traversal outside of the template root directories.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-22"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 4.9
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:S/C:P/I:N/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:N",
              "V2Score": 4,
              "V3Score": 4.9
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 4.9
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2021-33203",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-33203",
            "https://docs.djangoproject.com/en/3.2/releases/security/",
            "https://github.com/advisories/GHSA-68w8-qjq3-2gfm",
            "https://github.com/django/django/commit/053cc9534d174dc89daba36724ed2dcb36755b90",
            "https://groups.google.com/forum/#!forum/django-announce",
            "https://linux.oracle.com/cve/CVE-2021-33203.html",
            "https://linux.oracle.com/errata/ELSA-2022-9341.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-33203",
            "https://security.netapp.com/advisory/ntap-20210727-0004/",
            "https://ubuntu.com/security/notices/USN-4975-1",
            "https://ubuntu.com/security/notices/USN-4975-2",
            "https://www.djangoproject.com/weblog/2021/jun/02/security-releases/"
          ],
          "PublishedDate": "2021-06-08T18:15:00Z",
          "LastModifiedDate": "2022-02-25T18:42:00Z"
        },
        {
          "VulnerabilityID": "CVE-2020-25626",
          "PkgName": "djangorestframework",
          "InstalledVersion": "3.9.2",
          "FixedVersion": "3.11.2",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-25626",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "django-rest-framework: XSS Vulnerability in API viewer",
          "Description": "A flaw was found in Django REST Framework versions before 3.12.0 and before 3.11.2. When using the browseable API viewer, Django REST Framework fails to properly escape certain strings that can come from user input. This allows a user who can control those strings to inject malicious \u003cscript\u003e tags, leading to a cross-site-scripting (XSS) vulnerability.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-79"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V3Score": 6.1
            },
            "nvd": {
              "V2Vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V2Score": 4.3,
              "V3Score": 6.1
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N",
              "V3Score": 5.4
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2020-25626",
            "https://bugzilla.redhat.com/show_bug.cgi?id=1878635",
            "https://github.com/advisories/GHSA-fx83-3ph3-9j2q",
            "https://nvd.nist.gov/vuln/detail/CVE-2020-25626",
            "https://security.netapp.com/advisory/ntap-20201016-0003/",
            "https://www.debian.org/security/2022/dsa-5186"
          ],
          "PublishedDate": "2020-09-30T20:15:00Z",
          "LastModifiedDate": "2022-09-28T19:35:00Z"
        },
        {
          "VulnerabilityID": "CVE-2022-30034",
          "PkgName": "flower",
          "InstalledVersion": "0.9.3",
          "FixedVersion": "1.2.0",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-30034",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory Pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "Flower OAuth authentication bypass",
          "Description": "Flower, a web UI for the Celery Python RPC framework, all versions as of 05-02-2022 is vulnerable to an OAuth authentication bypass. An attacker could then access the Flower API to discover and invoke arbitrary Celery RPC calls or deny service by shutting down Celery task nodes.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-287"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:H",
              "V3Score": 8.6
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:H",
              "V2Score": 7.5,
              "V3Score": 8.6
            }
          },
          "References": [
            "http://githubcommherflower.com",
            "https://github.com/advisories/GHSA-q4qm-xhf9-4p8f",
            "https://github.com/mher/flower/issues/1217",
            "https://github.com/mher/flower/pull/1216",
            "https://github.com/pypa/advisory-database/tree/main/vulns/flower/PYSEC-2022-42973.yaml",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-30034",
            "https://tprynn.github.io/2022/05/26/flower-vulns.html"
          ],
          "PublishedDate": "2022-06-02T14:15:00Z",
          "LastModifiedDate": "2022-10-26T22:48:00Z"
        },
        {
          "VulnerabilityID": "CVE-2021-21240",
          "PkgName": "httplib2",
          "InstalledVersion": "0.12.1",
          "FixedVersion": "0.19.0",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-21240",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "python-httplib2: Regular expression denial of service via malicious header",
          "Description": "httplib2 is a comprehensive HTTP client library for Python. In httplib2 before version 0.19.0, a malicious server which responds with long series of \"\\xa0\" characters in the \"www-authenticate\" header may cause Denial of Service (CPU burn while parsing header) of the httplib2 client accessing said server. This is fixed in version 0.19.0 which contains a new implementation of auth headers parsing using the pyparsing library.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-400"
          ],
          "CVSS": {
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V2Score": 5,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2021-21240",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-21240",
            "https://github.com/advisories/GHSA-93xj-8mrv-444m",
            "https://github.com/httplib2/httplib2/commit/bd9ee252c8f099608019709e22c0d705e98d26bc",
            "https://github.com/httplib2/httplib2/pull/182",
            "https://github.com/httplib2/httplib2/security/advisories/GHSA-93xj-8mrv-444m",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-21240",
            "https://pypi.org/project/httplib2"
          ],
          "PublishedDate": "2021-02-08T20:15:00Z",
          "LastModifiedDate": "2021-02-12T14:56:00Z"
        },
        {
          "VulnerabilityID": "CVE-2020-11078",
          "PkgName": "httplib2",
          "InstalledVersion": "0.12.1",
          "FixedVersion": "0.18.0",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-11078",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "python-httplib2: CRLF injection via an attacker controlled unescaped part of uri for httplib2.Http.request function",
          "Description": "In httplib2 before version 0.18.0, an attacker controlling unescaped part of uri for `httplib2.Http.request()` could change request headers and body, send additional hidden requests to same server. This vulnerability impacts software that uses httplib2 with uri constructed by string concatenation, as opposed to proper urllib building with escaping. This has been fixed in 0.18.0.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-93",
            "CWE-74"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:N/I:H/A:N",
              "V3Score": 6.8
            },
            "nvd": {
              "V2Vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:N/I:H/A:N",
              "V2Score": 4.3,
              "V3Score": 6.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:N/I:H/A:N",
              "V3Score": 6.8
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2020-11078",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-11078",
            "https://github.com/advisories/GHSA-gg84-qgv9-w4pq",
            "https://github.com/httplib2/httplib2/commit/a1457cc31f3206cf691d11d2bf34e98865873e9e",
            "https://github.com/httplib2/httplib2/security/advisories/GHSA-gg84-qgv9-w4pq",
            "https://linux.oracle.com/cve/CVE-2020-11078.html",
            "https://linux.oracle.com/errata/ELSA-2020-5947.html",
            "https://lists.apache.org/thread.html/r23711190c2e98152cb6f216b95090d5eeb978543bb7e0bad22ce47fc@%3Cissues.beam.apache.org%3E",
            "https://lists.apache.org/thread.html/r4d35dac106fab979f0db75a07fc4e320ad848b722103e79667ff99e1@%3Cissues.beam.apache.org%3E",
            "https://lists.apache.org/thread.html/r69a462e690b5f2c3d418a288a2c98ae764d58587bd0b5d6ab141f25f@%3Cissues.beam.apache.org%3E",
            "https://lists.apache.org/thread.html/r7f364000066748299b331b615ba51c62f55ab5b201ddce9a22d98202@%3Cissues.beam.apache.org%3E",
            "https://lists.apache.org/thread.html/rad8872fc99f670958c2774e2bf84ee32a3a0562a0c787465cf3dfa23@%3Cissues.beam.apache.org%3E",
            "https://lists.apache.org/thread.html/rc9eff9572946142b657c900fe63ea4bbd3535911e8d4ce4d08fe4b89@%3Ccommits.allura.apache.org%3E",
            "https://lists.debian.org/debian-lts-announce/2020/06/msg00000.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IXCX2AWROGWGY5GXR7VN3BKF34A2FO6J/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PZJ3D6JSM7CFZESZZKGUW2VX55BOSOXI/",
            "https://nvd.nist.gov/vuln/detail/CVE-2020-11078"
          ],
          "PublishedDate": "2020-05-20T16:15:00Z",
          "LastModifiedDate": "2020-08-19T18:56:00Z"
        },
        {
          "VulnerabilityID": "CVE-2020-28493",
          "PkgName": "jinja2",
          "InstalledVersion": "2.10.1",
          "FixedVersion": "2.11.3",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-28493",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "python-jinja2: ReDoS vulnerability in the urlize filter",
          "Description": "This affects the package jinja2 from 0.0.0 and before 2.11.3. The ReDoS vulnerability is mainly due to the `_punctuation_re regex` operator and its use of multiple wildcards. The last wildcard is the most exploitable as it searches for trailing punctuation. This issue can be mitigated by Markdown to format user content instead of the urlize filter, or by implementing request timeouts and limiting process memory.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-400"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
              "V3Score": 5.3
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
              "V2Score": 5,
              "V3Score": 5.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2020-28493.json",
            "https://access.redhat.com/security/cve/CVE-2020-28493",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-28493",
            "https://errata.almalinux.org/8/ALSA-2021-4162.html",
            "https://github.com/advisories/GHSA-g3rq-g295-4j3m",
            "https://github.com/pallets/jinja/blob/ab81fd9c277900c85da0c322a2ff9d68a235b2e6/src/jinja2/utils.py%23L20",
            "https://github.com/pallets/jinja/pull/1343",
            "https://github.com/yetingli/PoCs/tree/main/CVE-2020-28493",
            "https://linux.oracle.com/cve/CVE-2020-28493.html",
            "https://linux.oracle.com/errata/ELSA-2021-4162.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PVAKCOO7VBVUBM3Q6CBBTPBFNP5NDXF4/",
            "https://nvd.nist.gov/vuln/detail/CVE-2020-28493",
            "https://security.gentoo.org/glsa/202107-19",
            "https://snyk.io/vuln/SNYK-PYTHON-JINJA2-1012994",
            "https://ubuntu.com/security/notices/USN-5701-1"
          ],
          "PublishedDate": "2021-02-01T20:15:00Z",
          "LastModifiedDate": "2022-04-08T14:05:00Z"
        },
        {
          "VulnerabilityID": "CVE-2020-29651",
          "PkgName": "py",
          "InstalledVersion": "1.8.0",
          "FixedVersion": "1.10.0",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-29651",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "python-py: ReDoS in the py.path.svnwc component via mailicious input to blame functionality",
          "Description": "A denial of service via regular expression in the py.path.svnwc component of py (aka python-py) through 1.9.0 could be used by attackers to cause a compute-time denial of service attack by supplying malicious input to the blame functionality.",
          "Severity": "HIGH",
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V2Score": 5,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
              "V3Score": 4.3
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2020-29651",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-29651",
            "https://github.com/advisories/GHSA-hj5v-574p-mj7c",
            "https://github.com/pytest-dev/py/issues/256",
            "https://github.com/pytest-dev/py/pull/257",
            "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AYWNYEV3FGDHPIHX4DDUDMFZ6NLCQRC4/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CHDTINIBJZ67T3W74QTBIY5LPKAXEOGR/",
            "https://nvd.nist.gov/vuln/detail/CVE-2020-29651",
            "https://ubuntu.com/security/notices/USN-5138-1",
            "https://www.oracle.com/security-alerts/cpujul2022.html"
          ],
          "PublishedDate": "2020-12-09T07:15:00Z",
          "LastModifiedDate": "2022-10-12T17:08:00Z"
        },
        {
          "VulnerabilityID": "CVE-2022-42969",
          "PkgName": "py",
          "InstalledVersion": "1.8.0",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-42969",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "The py library through 1.11.0 for Python allows remote attackers to co ...",
          "Description": "The py library through 1.11.0 for Python allows remote attackers to conduct a ReDoS (Regular expression Denial of Service) attack via a Subversion repository with crafted info data, because the InfoSvnCommand argument is mishandled.",
          "Severity": "HIGH",
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
              "V3Score": 5.3
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://github.com/advisories/GHSA-w596-4wvx-j9j6",
            "https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316",
            "https://github.com/pytest-dev/py/issues/287",
            "https://github.com/pytest-dev/py/issues/288",
            "https://github.com/pytest-dev/pytest/issues/10392",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-42969",
            "https://pypi.org/project/py"
          ],
          "PublishedDate": "2022-10-16T06:15:00Z",
          "LastModifiedDate": "2022-10-18T19:50:00Z"
        },
        {
          "VulnerabilityID": "CVE-2021-20270",
          "PkgName": "pygments",
          "InstalledVersion": "2.3.1",
          "FixedVersion": "2.7.4",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-20270",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "python-pygments: Infinite loop in SML lexer may lead to DoS",
          "Description": "An infinite loop in SMLLexer in Pygments versions 1.5 to 2.7.3 may lead to denial of service when performing syntax highlighting of a Standard ML (SML) source file, as demonstrated by input that only contains the \"exception\" keyword.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-835"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V2Score": 5,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2021-20270",
            "https://bugzilla.redhat.com/show_bug.cgi?id=1922136",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-20270",
            "https://errata.almalinux.org/8/ALSA-2021-4151.html",
            "https://github.com/advisories/GHSA-9w8r-397f-prfh",
            "https://linux.oracle.com/cve/CVE-2021-20270.html",
            "https://linux.oracle.com/errata/ELSA-2021-9553.html",
            "https://lists.debian.org/debian-lts-announce/2021/05/msg00003.html",
            "https://lists.debian.org/debian-lts-announce/2021/05/msg00006.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-20270",
            "https://ubuntu.com/security/notices/USN-4885-1",
            "https://www.debian.org/security/2021/dsa-4889",
            "https://www.oracle.com/security-alerts/cpuoct2021.html"
          ],
          "PublishedDate": "2021-03-23T17:15:00Z",
          "LastModifiedDate": "2021-12-10T17:04:00Z"
        },
        {
          "VulnerabilityID": "CVE-2021-27291",
          "PkgName": "pygments",
          "InstalledVersion": "2.3.1",
          "FixedVersion": "2.7.4",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-27291",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "python-pygments: ReDoS in multiple lexers",
          "Description": "In pygments 1.1+, fixed in 2.7.4, the lexers used to parse programming languages rely heavily on regular expressions. Some of the regular expressions have exponential or cubic worst-case complexity and are vulnerable to ReDoS. By crafting malicious input, an attacker can cause a denial of service.",
          "Severity": "HIGH",
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V2Score": 5,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2021-27291",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-27291",
            "https://errata.almalinux.org/8/ALSA-2021-4151.html",
            "https://gist.github.com/b-c-ds/b1a2cc0c68a35c57188575eb496de5ce",
            "https://github.com/advisories/GHSA-pq64-v7f5-gqh8",
            "https://github.com/pygments/pygments/commit/2e7e8c4a7b318f4032493773732754e418279a14",
            "https://linux.oracle.com/cve/CVE-2021-27291.html",
            "https://linux.oracle.com/errata/ELSA-2021-9553.html",
            "https://lists.debian.org/debian-lts-announce/2021/03/msg00024.html",
            "https://lists.debian.org/debian-lts-announce/2021/05/msg00003.html",
            "https://lists.debian.org/debian-lts-announce/2021/05/msg00006.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GSJRFHALQ7E3UV4FFMFU2YQ6LUDHAI55/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WSLD67LFGXOX2K5YNESSWAS4AGZIJTUQ/",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-27291",
            "https://ubuntu.com/security/notices/USN-4897-1",
            "https://www.debian.org/security/2021/dsa-4878",
            "https://www.debian.org/security/2021/dsa-4889"
          ],
          "PublishedDate": "2021-03-17T13:15:00Z",
          "LastModifiedDate": "2022-05-23T22:35:00Z"
        },
        {
          "VulnerabilityID": "CVE-2022-29217",
          "PkgName": "pyjwt",
          "InstalledVersion": "1.7.1",
          "FixedVersion": "2.4.0",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-29217",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "python-jwt: Key confusion through non-blocklisted public key formats",
          "Description": "PyJWT is a Python implementation of RFC 7519. PyJWT supports multiple different JWT signing algorithms. With JWT, an attacker submitting the JWT token can choose the used signing algorithm. The PyJWT library requires that the application chooses what algorithms are supported. The application can specify `jwt.algorithms.get_default_algorithms()` to get support for all algorithms, or specify a single algorithm. The issue is not that big as `algorithms=jwt.algorithms.get_default_algorithms()` has to be used. Users should upgrade to v2.4.0 to receive a patch for this issue. As a workaround, always be explicit with the algorithms that are accepted and expected when decoding.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-327"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
              "V3Score": 7.4
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V2Score": 5,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2022-29217",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-29217",
            "https://github.com/advisories/GHSA-ffqj-6fqr-9h24",
            "https://github.com/jpadilla/pyjwt/commit/9c528670c455b8d948aff95ed50e22940d1ad3fc",
            "https://github.com/jpadilla/pyjwt/commit/9c528670c455b8d948aff95ed50e22940d1ad3fc (2.4.0)",
            "https://github.com/jpadilla/pyjwt/releases/tag/2.4.0",
            "https://github.com/jpadilla/pyjwt/security/advisories/GHSA-ffqj-6fqr-9h24",
            "https://github.com/pypa/advisory-database/tree/main/vulns/pyjwt/PYSEC-2022-202.yaml",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5PK7IQCBVNLYJEFTPHBBPFP72H4WUFNX/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6HIYEYZRQEP6QTHT3EHH3RGFYJIHIMAO/",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-29217",
            "https://ubuntu.com/security/notices/USN-5526-1",
            "https://ubuntu.com/security/notices/USN-5526-2"
          ],
          "PublishedDate": "2022-05-24T15:15:00Z",
          "LastModifiedDate": "2022-06-07T14:40:00Z"
        },
        {
          "VulnerabilityID": "CVE-2019-20477",
          "PkgName": "pyyaml",
          "InstalledVersion": "5.1",
          "FixedVersion": "5.2b1",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-20477",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "PyYAML: command execution through python/object/apply constructor in FullLoader",
          "Description": "PyYAML 5.1 through 5.1.2 has insufficient restrictions on the load and load_all functions because of a class deserialization issue, e.g., Popen is a class in the subprocess module. NOTE: this issue exists because of an incomplete fix for CVE-2017-18342.",
          "Severity": "CRITICAL",
          "CweIDs": [
            "CWE-502"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V2Score": 7.5,
              "V3Score": 9.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2019-20477",
            "https://errata.almalinux.org/8/ALSA-2020-4641.html",
            "https://github.com/advisories/GHSA-3pqx-4fqf-j49f",
            "https://github.com/yaml/pyyaml/blob/master/CHANGES",
            "https://linux.oracle.com/cve/CVE-2019-20477.html",
            "https://linux.oracle.com/errata/ELSA-2020-4641.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/33VBUY73AA6CTTYL3LRWHNFDULV7PFPN/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/52N5XS73Z5S4ZN7I7R56ICCPCTKCUV4H/",
            "https://nvd.nist.gov/vuln/detail/CVE-2019-20477",
            "https://www.exploit-db.com/download/47655"
          ],
          "PublishedDate": "2020-02-19T04:15:00Z",
          "LastModifiedDate": "2022-01-01T19:38:00Z"
        },
        {
          "VulnerabilityID": "CVE-2020-14343",
          "PkgName": "pyyaml",
          "InstalledVersion": "5.1",
          "FixedVersion": "5.4",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-14343",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "PyYAML: incomplete fix for CVE-2020-1747",
          "Description": "A vulnerability was discovered in the PyYAML library in versions before 5.4, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747.",
          "Severity": "CRITICAL",
          "CweIDs": [
            "CWE-20",
            "CWE-20"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:C/I:C/A:C",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V2Score": 10,
              "V3Score": 9.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2020-14343",
            "https://bugzilla.redhat.com/show_bug.cgi?id=1860466",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-14343",
            "https://errata.almalinux.org/8/ALSA-2021-2583.html",
            "https://github.com/advisories/GHSA-8q59-q68h-6hv4",
            "https://github.com/yaml/pyyaml/commit/a001f2782501ad2d24986959f0239a354675f9dc",
            "https://github.com/yaml/pyyaml/issues/420#issuecomment-663673966",
            "https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation",
            "https://linux.oracle.com/cve/CVE-2020-14343.html",
            "https://linux.oracle.com/errata/ELSA-2021-2583.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2020-14343",
            "https://pypi.org/project/PyYAML/",
            "https://ubuntu.com/security/notices/USN-4940-1",
            "https://www.oracle.com/security-alerts/cpuapr2022.html",
            "https://www.oracle.com/security-alerts/cpujul2022.html"
          ],
          "PublishedDate": "2021-02-09T21:15:00Z",
          "LastModifiedDate": "2022-07-25T18:15:00Z"
        },
        {
          "VulnerabilityID": "CVE-2020-1747",
          "PkgName": "pyyaml",
          "InstalledVersion": "5.1",
          "FixedVersion": "5.3.1",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-1747",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "PyYAML: arbitrary command execution through python/object/new when FullLoader is used",
          "Description": "A vulnerability was discovered in the PyYAML library in versions before 5.3.1, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. An attacker could use this flaw to execute arbitrary code on the system by abusing the python/object/new constructor.",
          "Severity": "CRITICAL",
          "CweIDs": [
            "CWE-20"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:C/I:C/A:C",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V2Score": 10,
              "V3Score": 9.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            }
          },
          "References": [
            "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00017.html",
            "http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00017.html",
            "https://access.redhat.com/security/cve/CVE-2020-1747",
            "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1747",
            "https://errata.almalinux.org/8/ALSA-2020-4641.html",
            "https://github.com/advisories/GHSA-6757-jp84-gxfx",
            "https://github.com/yaml/pyyaml/pull/386",
            "https://linux.oracle.com/cve/CVE-2020-1747.html",
            "https://linux.oracle.com/errata/ELSA-2020-4641.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7PPAS6C4SZRDQLR7C22A5U3QOLXY33JX/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K5HEPD7LEVDPCITY5IMDYWXUMX37VFMY/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MMQXSZXNJT6ERABJZAAICI3DQSQLCP3D/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WORRFHPQVAFKKXXWLSSW6XKUYLWM6CSH/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBJA3SGNJKCAYPSHOHWY3KBCWNM5NYK2/",
            "https://nvd.nist.gov/vuln/detail/CVE-2020-1747",
            "https://www.oracle.com/security-alerts/cpujul2022.html"
          ],
          "PublishedDate": "2020-03-24T15:15:00Z",
          "LastModifiedDate": "2022-07-25T18:15:00Z"
        },
        {
          "VulnerabilityID": "CVE-2021-32839",
          "PkgName": "sqlparse",
          "InstalledVersion": "0.3.0",
          "FixedVersion": "0.4.2",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-32839",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "python-sqlparse: ReDoS via regular expression in StripComments filter",
          "Description": "sqlparse is a non-validating SQL parser module for Python. In sqlparse versions 0.4.0 and 0.4.1 there is a regular Expression Denial of Service in sqlparse vulnerability. The regular expression may cause exponential backtracking on strings containing many repetitions of '\\r\\n' in SQL comments. Only the formatting feature that removes comments from SQL statements is affected by this regular expression. As a workaround don't use the sqlformat.format function with keyword strip_comments=True or the --strip-comments command line flag when using the sqlformat command line tool. The issues has been fixed in sqlparse 0.4.2.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-400"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V2Score": 5,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2021-32839",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-32839",
            "https://github.com/advisories/GHSA-p5w8-wqhj-9hhf",
            "https://github.com/andialbrecht/sqlparse/commit/8238a9e450ed1524e40cb3a8b0b3c00606903aeb",
            "https://github.com/andialbrecht/sqlparse/security/advisories/GHSA-p5w8-wqhj-9hhf",
            "https://github.com/pypa/advisory-database/tree/main/vulns/sqlparse/PYSEC-2021-333.yaml",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-32839",
            "https://securitylab.github.com/advisories/GHSL-2021-107-andialbrecht-sqlparse/",
            "https://ubuntu.com/security/notices/USN-5085-1"
          ],
          "PublishedDate": "2021-09-20T17:15:00Z",
          "LastModifiedDate": "2021-09-29T15:04:00Z"
        },
        {
          "VulnerabilityID": "CVE-2019-11324",
          "PkgName": "urllib3",
          "InstalledVersion": "1.24.1",
          "FixedVersion": "1.24.2",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-11324",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "python-urllib3: Certification mishandle when error should be thrown",
          "Description": "The urllib3 library before 1.24.2 for Python mishandles certain cases where the desired set of CA certificates is different from the OS store of CA certificates, which results in SSL connections succeeding in situations where a verification failure is the correct outcome. This is related to use of the ssl_context, ca_certs, or ca_certs_dir argument.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-295"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V2Score": 5,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            }
          },
          "References": [
            "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html",
            "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00041.html",
            "http://www.openwall.com/lists/oss-security/2019/04/19/1",
            "https://access.redhat.com/errata/RHSA-2019:3335",
            "https://access.redhat.com/errata/RHSA-2019:3590",
            "https://access.redhat.com/security/cve/CVE-2019-11324",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-11324",
            "https://errata.almalinux.org/8/ALSA-2020-1605.html",
            "https://github.com/advisories/GHSA-mh33-7rrq-662w",
            "https://github.com/urllib3/urllib3/compare/a6ec68a...1efadf4",
            "https://linux.oracle.com/cve/CVE-2019-11324.html",
            "https://linux.oracle.com/errata/ELSA-2020-2068.html",
            "https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NKGPJLVLVYCL4L4B4G5TIOTVK4BKPG72/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XOSA2NT4DUQDBEIWE6O7KKD24XND7TE2/",
            "https://nvd.nist.gov/vuln/detail/CVE-2019-11324",
            "https://pypi.org/project/urllib3/1.24.2/",
            "https://ubuntu.com/security/notices/USN-3990-1",
            "https://usn.ubuntu.com/3990-1/",
            "https://www.openwall.com/lists/oss-security/2019/04/17/3"
          ],
          "PublishedDate": "2019-04-18T21:29:00Z",
          "LastModifiedDate": "2021-06-15T21:15:00Z"
        },
        {
          "VulnerabilityID": "CVE-2021-33503",
          "PkgName": "urllib3",
          "InstalledVersion": "1.24.1",
          "FixedVersion": "1.26.5",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-33503",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "python-urllib3: ReDoS in the parsing of authority part of URL",
          "Description": "An issue was discovered in urllib3 before 1.26.5. When provided with a URL containing many @ characters in the authority component, the authority regular expression exhibits catastrophic backtracking, causing a denial of service if a URL were passed as a parameter or redirected to via an HTTP redirect.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-400"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V2Score": 5,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2021-33503",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-33503",
            "https://errata.almalinux.org/8/ALSA-2021-4162.html",
            "https://github.com/advisories/GHSA-q2q7-5pp4-w6pg",
            "https://github.com/urllib3/urllib3/commit/2d4a3fee6de2fa45eb82169361918f759269b4ec",
            "https://github.com/urllib3/urllib3/commit/5b047b645f5f93900d5e2fc31230848c25eb1f5f#diff-52026d639119bf1e0364836b4e8a18bd9ed3c95c6ba39b26534a5057a65e35bbR65",
            "https://github.com/urllib3/urllib3/security/advisories/GHSA-q2q7-5pp4-w6pg",
            "https://linux.oracle.com/cve/CVE-2021-33503.html",
            "https://linux.oracle.com/errata/ELSA-2021-4162.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6SCV7ZNAHS3E6PBFLJGENCDRDRWRZZ6W/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FMUGWEAUYGGHTPPXT6YBD53WYXQGVV73/",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-33503",
            "https://security.gentoo.org/glsa/202107-36",
            "https://www.oracle.com/security-alerts/cpuoct2021.html"
          ],
          "PublishedDate": "2021-06-29T11:15:00Z",
          "LastModifiedDate": "2021-12-08T20:34:00Z"
        },
        {
          "VulnerabilityID": "CVE-2019-11236",
          "PkgName": "urllib3",
          "InstalledVersion": "1.24.1",
          "FixedVersion": "1.24.3",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-11236",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "python-urllib3: CRLF injection due to not encoding the '\\r\\n' sequence leading to possible attack on internal service",
          "Description": "In the urllib3 library through 1.24.1 for Python, CRLF injection is possible if the attacker controls the request parameter.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-93"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V3Score": 6.1
            },
            "nvd": {
              "V2Vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V2Score": 4.3,
              "V3Score": 6.1
            },
            "redhat": {
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
              "V3Score": 6.5
            }
          },
          "References": [
            "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html",
            "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00041.html",
            "https://access.redhat.com/errata/RHSA-2019:2272",
            "https://access.redhat.com/errata/RHSA-2019:3335",
            "https://access.redhat.com/errata/RHSA-2019:3590",
            "https://access.redhat.com/security/cve/CVE-2019-11236",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-11236",
            "https://errata.almalinux.org/8/ALSA-2020-1605.html",
            "https://github.com/advisories/GHSA-r64q-w8jr-g9qp",
            "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2019-132.yaml",
            "https://github.com/urllib3/urllib3/issues/1553",
            "https://linux.oracle.com/cve/CVE-2019-11236.html",
            "https://linux.oracle.com/errata/ELSA-2020-2081.html",
            "https://lists.debian.org/debian-lts-announce/2019/06/msg00016.html",
            "https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NKGPJLVLVYCL4L4B4G5TIOTVK4BKPG72/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/R62XGEYPUTXMRHGX5I37EBCGQ5COHGKR/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TBI45HO533KYHNB5YRO43TBYKA3E3VRL/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XOSA2NT4DUQDBEIWE6O7KKD24XND7TE2/",
            "https://nvd.nist.gov/vuln/detail/CVE-2019-11236",
            "https://ubuntu.com/security/notices/USN-3990-1",
            "https://ubuntu.com/security/notices/USN-3990-2",
            "https://usn.ubuntu.com/3990-1/",
            "https://usn.ubuntu.com/3990-2/"
          ],
          "PublishedDate": "2019-04-15T15:29:00Z",
          "LastModifiedDate": "2021-06-15T21:15:00Z"
        },
        {
          "VulnerabilityID": "CVE-2020-26137",
          "PkgName": "urllib3",
          "InstalledVersion": "1.24.1",
          "FixedVersion": "1.25.9",
          "Layer": {},
          "SeveritySource": "nvd",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-26137",
          "DataSource": {
            "ID": "osv",
            "Name": "Python Packaging Advisory Database",
            "URL": "https://github.com/pypa/advisory-db"
          },
          "Title": "python-urllib3: CRLF injection via HTTP request method",
          "Description": "urllib3 before 1.25.9 allows CRLF injection if the attacker controls the HTTP request method, as demonstrated by inserting CR and LF control characters in the first argument of putrequest(). NOTE: this is similar to CVE-2020-26116.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-74"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
              "V3Score": 6.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
              "V2Score": 6.4,
              "V3Score": 6.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
              "V3Score": 6.5
            }
          },
          "References": [
            "https://access.redhat.com/hydra/rest/securitydata/cve/CVE-2020-26137.json",
            "https://access.redhat.com/security/cve/CVE-2020-26137",
            "https://bugs.python.org/issue39603",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-26137",
            "https://errata.almalinux.org/8/ALSA-2021-1761.html",
            "https://github.com/advisories/GHSA-wqvq-5m8c-6g24",
            "https://github.com/urllib3/urllib3/commit/1dd69c5c5982fae7c87a620d487c2ebf7a6b436b",
            "https://github.com/urllib3/urllib3/pull/1800",
            "https://linux.oracle.com/cve/CVE-2020-26137.html",
            "https://linux.oracle.com/errata/ELSA-2022-5235.html",
            "https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2020-26137",
            "https://ubuntu.com/security/notices/USN-4570-1",
            "https://usn.ubuntu.com/4570-1/",
            "https://www.oracle.com/security-alerts/cpujul2022.html",
            "https://www.oracle.com/security-alerts/cpuoct2021.html"
          ],
          "PublishedDate": "2020-09-30T18:15:00Z",
          "LastModifiedDate": "2022-07-25T18:15:00Z"
        }
      ]
    }
  ]
}
